parcelRequire=function(e,r,t,n){var i,o="function"==typeof parcelRequire&&parcelRequire,u="function"==typeof require&&require;function f(t,n){if(!r[t]){if(!e[t]){var i="function"==typeof parcelRequire&&parcelRequire;if(!n&&i)return i(t,!0);if(o)return o(t,!0);if(u&&"string"==typeof t)return u(t);var c=new Error("Cannot find module '"+t+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[t][1][r]||r},p.cache={};var l=r[t]=new f.Module(t);e[t][0].call(l.exports,p,l,l.exports,this)}return r[t].exports;function p(e){return f(p.resolve(e))}}f.isParcelRequire=!0,f.Module=function(e){this.id=e,this.bundle=f,this.exports={}},f.modules=e,f.cache=r,f.parent=o,f.register=function(r,t){e[r]=[function(e,r){r.exports=t},{}]};for(var c=0;c<t.length;c++)try{f(t[c])}catch(e){i||(i=e)}if(t.length){var l=f(t[t.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=l:"function"==typeof define&&define.amd?define(function(){return l}):n&&(this[n]=l)}if(parcelRequire=f,i)throw i;return f}({"z5Lg":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.FirebaseProvider=exports.FirebaseContext=void 0;var e=o(require("react")),t=r(require("firebase/app"));function r(e){return e&&e.__esModule?e:{default:e}}function n(){if("function"!=typeof WeakMap)return null;var e=new WeakMap;return n=function(){return e},e}function o(e){if(e&&e.__esModule)return e;if(null===e||"object"!=typeof e&&"function"!=typeof e)return{default:e};var t=n();if(t&&t.has(e))return t.get(e);var r={},o=Object.defineProperty&&Object.getOwnPropertyDescriptor;for(var i in e)if(Object.prototype.hasOwnProperty.call(e,i)){var a=o?Object.getOwnPropertyDescriptor(e,i):null;a&&(a.get||a.set)?Object.defineProperty(r,i,a):r[i]=e[i]}return r.default=e,t&&t.set(e,r),r}const i=(0,e.createContext)(null);exports.FirebaseContext=i;const a=({children:r,firebaseConfig:n})=>(t.default.apps.length||t.default.initializeApp(n),e.default.createElement(i.Provider,{value:t.default},r));exports.FirebaseProvider=a;
},{}],"aWYP":[function(require,module,exports) {
"use strict";function e(e){for(let t=e.length-1;t>0;t--){const o=Math.floor(Math.random()*(t+1));[e[t],e[o]]=[e[o],e[t]]}return e}Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var t=e;exports.default=t;
},{}],"zziC":[function(require,module,exports) {
module.exports="/adjectives.8f551c60.data";
},{}],"kD2g":[function(require,module,exports) {
module.exports="/nouns.2864811e.data";
},{}],"LimT":[function(require,module,exports) {

},{}],"iE4K":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=l(require("react")),t=require("./firebase"),a=n(require("./shuffle"));require("firebase/database");var r=n(require("oboe"));function n(e){return e&&e.__esModule?e:{default:e}}function u(){if("function"!=typeof WeakMap)return null;var e=new WeakMap;return u=function(){return e},e}function l(e){if(e&&e.__esModule)return e;if(null===e||"object"!=typeof e&&"function"!=typeof e)return{default:e};var t=u();if(t&&t.has(e))return t.get(e);var a={},r=Object.defineProperty&&Object.getOwnPropertyDescriptor;for(var n in e)if(Object.prototype.hasOwnProperty.call(e,n)){var l=r?Object.getOwnPropertyDescriptor(e,n):null;l&&(l.get||l.set)?Object.defineProperty(a,n,l):a[n]=e[n]}return a.default=e,t&&t.set(e,a),a}const o=require("./adjectives.data"),f=require("./nouns.data");require("./intro.scss");var s=({playerName:t,setPlayerName:a,setGameId:r,onStart:n,gameIntro:u})=>e.default.createElement("intro-block",null,e.default.createElement("h2",null,"Welcome"),u,e.default.createElement(c,{playerName:t,setPlayerName:a,setGameId:r,onStart:n}));exports.default=s;const c=({playerName:n,setPlayerName:u,setGameId:l,onStart:s})=>{const[c,d]=(0,e.useState)(""),[i,m]=(0,e.useState)(!1),[p,y]=(0,e.useState)([]),[b,g]=(0,e.useState)([]),[v,h]=(0,e.useState)(0),E=(0,e.useContext)(t.FirebaseContext),P=()=>{""!==c&&""!==n?Promise.resolve().then(()=>{m(!0)}).then(()=>E.database().ref(`/${c}/players`)).then(e=>e.push({name:n})).then(()=>l(c)):alert("You need both a name and gameId")};(0,e.useEffect)(()=>{(0,r.default)(o).done(function(e){y((0,a.default)(e))}).fail(function(e){console.warn(e)}),(0,r.default)(f).done(function(e){g((0,a.default)(e))}).fail(function(e){console.warn(e)})},[]);return e.default.createElement(e.default.Fragment,null,e.default.createElement("input",{type:"text",placeholder:"Your name",value:n,onChange:e=>u(e.target.value)}),e.default.createElement("input",{type:"text",placeholder:"Enter the game code",value:c,onChange:e=>d(e.target.value),onKeyPress:e=>{"Enter"==e.key&&P()}}),!i&&e.default.createElement(e.default.Fragment,null,e.default.createElement("button",{onClick:()=>(()=>{const e=p[v],t=b[v];h(v+1),d(`${e}-${t}`)})()},"Suggest random game code"),e.default.createElement("button",{onClick:()=>P()},"Play!")))};
},{"./firebase":"z5Lg","./shuffle":"aWYP","./adjectives.data":"zziC","./nouns.data":"kD2g","./intro.scss":"LimT"}],"A2vr":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=a(require("react"));function a(e){return e&&e.__esModule?e:{default:e}}const t=({gameState:a,gameRef:t,playerName:l,onStart:r})=>{return a.players?e.default.createElement("players-list",null,e.default.createElement("h2",null,"Waiting to play"),Object.entries(a.players).map(([r,n])=>e.default.createElement("label",{key:n.name},e.default.createElement("player-name",null,n.name," is ",n.ready?"ready":"not ready"),n.name===l&&e.default.createElement("button",{onClick:()=>(e=>{let l=a.players;l[e].ready=!l[e].ready,t.update({players:l})})(r)},"Toggle if Ready"))),e.default.createElement("button",{onClick:()=>void(Object.values(a.players).some(e=>!e.ready)?alert("Someone isn't ready"):r({gameRef:t,gameState:a,playerName:l})),disabled:Object.values(a.players).some(e=>!e.ready)},"Start Game")):e.default.createElement("players-list",null," No players yet ")};var l=t;exports.default=l;
},{}],"Kid8":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=u(require("react")),t=require("./firebase");require("firebase/database");var r=a(require("./Lobby"));function a(e){return e&&e.__esModule?e:{default:e}}function n(){if("function"!=typeof WeakMap)return null;var e=new WeakMap;return n=function(){return e},e}function u(e){if(e&&e.__esModule)return e;if(null===e||"object"!=typeof e&&"function"!=typeof e)return{default:e};var t=n();if(t&&t.has(e))return t.get(e);var r={},a=Object.defineProperty&&Object.getOwnPropertyDescriptor;for(var u in e)if(Object.prototype.hasOwnProperty.call(e,u)){var l=a?Object.getOwnPropertyDescriptor(e,u):null;l&&(l.get||l.set)?Object.defineProperty(r,u,l):r[u]=e[u]}return r.default=e,t&&t.set(e,r),r}var l=({gameId:a,playerName:n,children:u,onStart:l})=>{const o=(0,e.useContext)(t.FirebaseContext),[f,i]=(0,e.useState)({}),[c,s]=(0,e.useState)();return(0,e.useEffect)(()=>{var e=o.database().ref(`/${a}/`);s(e),e.on("value",function(e){i(e.val())})},[]),e.default.createElement("game-container",null,e.default.createElement("game-title",null,"Game Id - ",a," - playing as ",n," ",e.default.createElement("a",{href:"/"},"New Game")),f.active?e.Children.map(u,t=>(0,e.cloneElement)(t,{gameState:f,gameRef:c,playerName:n})):e.default.createElement(r.default,{gameState:f,gameRef:c,playerName:n,onStart:l}))};exports.default=l;
},{"./firebase":"z5Lg","./Lobby":"A2vr"}],"tYUf":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=f(require("react")),r=require("./firebase"),t=require("react-use"),a=u(require("./Intro")),n=u(require("./GameAndLobby"));function u(e){return e&&e.__esModule?e:{default:e}}function o(){if("function"!=typeof WeakMap)return null;var e=new WeakMap;return o=function(){return e},e}function f(e){if(e&&e.__esModule)return e;if(null===e||"object"!=typeof e&&"function"!=typeof e)return{default:e};var r=o();if(r&&r.has(e))return r.get(e);var t={},a=Object.defineProperty&&Object.getOwnPropertyDescriptor;for(var n in e)if(Object.prototype.hasOwnProperty.call(e,n)){var u=a?Object.getOwnPropertyDescriptor(e,n):null;u&&(u.get||u.set)?Object.defineProperty(t,n,u):t[n]=e[n]}return t.default=e,r&&r.set(e,t),t}var i=({children:u,onStart:o=(()=>{}),gameIntro:f,firebaseConfig:i})=>{const[l,c]=(0,e.useState)((0,t.useSearchParam)("game")||""),[s,d]=(0,e.useState)((0,t.useSearchParam)("name")||"");return e.default.createElement(r.FirebaseProvider,{firebaseConfig:i},l?e.default.createElement(n.default,{gameId:l,playerName:s,onStart:o},u):e.default.createElement(a.default,{playerName:s,setPlayerName:d,setGameId:c,gameIntro:f}))};exports.default=i;
},{"./firebase":"z5Lg","./Intro":"iE4K","./GameAndLobby":"Kid8"}]},{},["tYUf"], null)
//# sourceMappingURL=/GameProvider.js.map